### PR TITLE
S3 bucket

### PR DESCRIPTION
**Pull request by k12kekeal**
- Avatar in UserInfoToolbar now re-renders if you upload a new image!
- You can now upload an image for a recipe when you submit a recipe through the Add Recipe button!
- I changed uploadAvatarToS3 -> uploadImageToS3 since we're not using it for both avatars and recipe images!

Co-authored by: @davidlichter & @rick-o-H (retroactively :^P)

### CODE REVIEW

**Comment by Doodlis** [comment]
just a quick question , are you using the same branch that was already merged?

**Comment by k12kekeal** [comment]
> just a quick question , are you using the same branch that was already merged?

yeah!

**Comment by Doodlis** [comment]
Most of the times when a branch was megred it is considered dead  and no one touches it anymore :)

**Comment by k12kekeal** [comment]
> Most of the times when a branch was megred it is considered dead and no one touches it anymore :)

ah, gotcha! should i switch these changes to a new branch or can we merge this one and then i'll delete it?

**Comment by rick-o-H** [comment]
I don't see an issue with merging this one as long as the latest development has been merged in with this one

**Review by rick-o-H — APPROVED** [review]
👍🔥

**Pull request merged**
